export const CHANGE_NAME = "CHANGE_NAME"
export const SET_NAME = "SET_NAME"

export const GET_UPCOMING_LAUNCHERS = "GET_UPCOMING_LAUNCHERS"
export const GET_UPCOMING_LAUNCHERS_SUCCESS = "GET_UPCOMING_LAUNCHERS_SUCCESS"

export const GET_LAUNCHER = "GET_LAUNCHER"
export const GET_LAUNCHER_SUCCESS = "GET_LAUNCHER_SUCCESS"

export const GET_ALL_HISTORY = "GET_ALL_HISTORY"
export const GET_ALL_HISTORY_SUCCESS = "GET_ALL_HISTORY_SUCCESS"

export const GET_HISTORY = "GET_HISTORY"
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS"
export const CLEAR_HISTORY = "CLEAR_HISTORY"